### ISSUE TITLE
systemd unit ulimit bug

### ISSUE THREAD

**Issue by brownc** [brianbianco/redisio#321] opened 2017-04-19 11:57 UTC
Consider this snippet from a chef role:

```
chef_type:           role
default_attributes:
  redisio:
    default_settings:
      ulimit:                50000
```

When Chef converges, on a CentOS 7 system with systemd, you get the following in your systemd unit file:

```
[Unit]
Description=Redis persistent key-value database
After=network.target

[Service]
ExecStart=/usr/bin/redis-server /etc/redis/%i.conf --daemonize no
ExecStop=/usr/bin/redis-shutdown
User=redis
Group=redis
LimitNOFILE=10032

[Install]
WantedBy=multi-user.target
```

The two don't match.

Turns out there's a two fold problem:

1) Commit 71469215cb3e1c7aedc78c8b3ab73a66881528a5 has put the systemd template file into recipes/configure.rb.  This is illogical bearing in mind that all the init.d scripts/etc and other config is dont in providers/configure.rb.

2) As a result of that, recipes/configure.rb can't make use of the "descriptors" variable that's calculated for the ulimit requirement that lives in providers/configure.rb.  Instead it's using "maxclients+32" to calculate the ulimit, which is different to the method in the provider (and makes ulimit defunct for systemd systems)

I was going to pop in a new branch and a PR to move the systemd template into the provider and then use "descriptors" to manage the ulimit for systemd, however, there's a couple of other major systemd enhancements already outstanding with pull requests which will likely clash.

Let me know if you want the above fix done anyway.  This is low priority anyway as some would probably argue why there's a need for such a differential.

In the meantime to workaround, set redisio/default_settings/maxclients attribute to what you want the ulimit to match to on systemd systems, and away you go.

Thanks!

**Comment by shortdudey123** [comment] 2017-04-26 07:36
Closes as dupe of https://github.com/brianbianco/redisio/issues/316

**Closed by shortdudey123** 2017-04-26 07:36 UTC

**Comment by brownc** [comment] 2017-04-28 16:47
It's done a lot of the tidy up but didn't fix the specific systemd issue I reported, working on a pull now for review.
